name: Release
on:
  push: { tags: 'v[0-9]+.[0-9]+.[0-9]+*' }

permissions: { contents: read }

jobs:
  github:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - run: gh release create ${tag/*-*/$tag --prerelease} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
          tag: ${{ github.ref_name }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
