name: Release
on:
  push: { tags: 'v[0-9]+.[0-9]+.[0-9]+*' }
permissions: {}

jobs:
  release:
    permissions: {contents: write, id-token: write}
    secrets: inherit
    uses: nodenv/.github/.github/workflows/release.yml@v4
    with:
      homebrew: false
      npm_scope: ''
