name: Release
on:
  push: { tags: 'v[0-9]+.[0-9]+.[0-9]+' }

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh release create --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
