name: Test
on: [push, pull_request, workflow_dispatch]

permissions: { contents: read }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm cit

  lint:
    runs-on: ubuntu-latest
    if: github.ref_name != github.event.repository.default_branch
    permissions: { statuses: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 } # super-linter needs full git history
      - uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_LOG_FILE: true
          BASH_EXEC_IGNORE_LIBRARIES: true
          FILTER_REGEX_EXCLUDE: '.*stub.*'
      - if: always()
        run: cat super-linter.log >> $GITHUB_STEP_SUMMARY
